#Stock-service configuration properties

---
server:
 port: 8084
spring:
 application:
   name: Stock-Service
 profiles:
   active:
   - dev
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Microservices
    username: postgres
    password: postgres
 jpa:
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update

---
server:
 port: 8084
spring:
 application:
   name: Stock-Service
 config:
   activate:
     on-profile:
     - qa
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Microservices
    username: postgres
    password: postgres
 jpa:
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update

---
server:
 port: 8084
spring:
 application:
   name: Stock-Service
 config:
   activate:
     on-profile:
     - prod
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Microservices
    username: postgres
    password: postgres
 jpa:
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update